apiVersion: v2
name: nextgen-eam
description: NextGen Enterprise Architecture Management
type: application
version: 1.4.3
appVersion: '1.4.3'
keywords:
  - enterprise-architecture
  - neo4j
  - graphql
  - keycloak
home: https://github.com/DE-FUE-CTO-COMMUNITY/simpleEAM
maintainers:
  - name: NextGen EAM Team
